export function ConfigParser() {
  return [
    {
      displayName: 'Store Light',
      lightPin: 13,
      buttonPin: 19,
      type: 'LightBulb',
      uniqueId: '12345aa5',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Wall Light',
      lightPin: 22,
      buttonPin: 20,
      type: 'LightBulb',
      uniqueId: '6485',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Center Light',
      lightPin: 27,
      buttonPin: 16,
      type: 'LightBulb',
      uniqueId: '6485112ss',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Side Light',
      lightPin: 17,
      buttonPin: 12,
      type: 'LightBulb',
      uniqueId: '648511gorrw2ss',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'TV Light',
      lightPin: 4,
      buttonPin: 24,
      type: 'LightBulb',
      uniqueId: '6tr4gorrw2ss',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Bar Light',
      lightPin: 3,
      buttonPin: 23,
      type: 'LightBulb',
      uniqueId: 'eeo33lpe11',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Store',
      motorUpPin: 5,
      motorDownPin: 6,
      buttonUpPin: 21,
      buttonDownPin: 26,
      type: 'WindowCovering',
      uniqueId: 'i2sdfdjh',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
  ];
}