export function ConfigParser() {
  return [
    {
      displayName: 'W C Light',
      lightPin: 13,
      buttonPin: 19,
      type: 'LightBulb',
      uniqueId: 'RLightBulb',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Hand Wash Light',
      lightPin: 6,
      buttonPin: 26,
      type: 'LightBulb',
      uniqueId: 'RLightBulb',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Bathroom Light',
      lightPin: 5,
      buttonPin: 21,
      type: 'LightBulb',
      uniqueId: 'RLightBulb',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Corodor Light',
      lightPin: 22,
      buttonPin: 20,
      type: 'LightBulb',
      uniqueId: 'RLightBulb',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Small Balcoon Light',
      lightPin: 27,
      buttonPin: 16,
      type: 'LightBulb',
      uniqueId: 'RLightBulb',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Mamad Light',
      lightPin: 17,
      buttonPin: 12,
      type: 'LightBulb',
      uniqueId: 'RLightBulb',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
    {
      displayName: 'Left Kichen',
      motorUpPin: 3,
      motorDownPin: 4,
      buttonUpPin: 23,
      buttonDownPin: 24,
      type: 'WindowCovering',
      uniqueId: 'RWindowCovering',
      Manufacturer: '',
      Model: '',
      SerialNumber: '',
    },
  ];
}